// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace CsBindgen
{
    public static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "unity_rsgen_sample";
#endif
        

        [DllImport(__DllName, EntryPoint = "my_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int my_add(int x, int y);

        [DllImport(__DllName, EntryPoint = "my_sub", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int my_sub(int x, int y);

        [DllImport(__DllName, EntryPoint = "my_multiply", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int my_multiply(int x, int y);

        [DllImport(__DllName, EntryPoint = "my_divide", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int my_divide(int x, int y);


    }



}
    